name: CI
"on":
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          pwd
          ls
          cd client
          ls
          npm install
      - name: Run Prettier
        run: |
          cd client
          npm run check
