name: CI
'on':
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        cd client
        npm install
    - name: Run Prettier
      run: |
        npm run check
